name: CI - Tests & Build

on:
  push:
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_OWNER: c-pierre
  IMAGE_REPO: ocr-projet-6

jobs:

  # JOB TESTS
  tests:
    name: Run tests (Back & Front)
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # Back-end tests (Gradle)
      - name: Set up JDK 20
        if: ${{ hashFiles('back/gradlew') != '' }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 20
          cache: gradle

      # Front-end tests (Node)
      - name: Set up Node.js
        if: ${{ hashFiles('front/package.json') != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: front/package-lock.json

      - name: Install Chrome
        if: ${{ hashFiles('front/package.json') != '' }}
        uses: browser-actions/setup-chrome@v1

      # Run unified test script
      - name: Run test script
        run: |
          chmod +x run-tests.sh
          ./run-tests.sh

      # Upload test results
      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            back/test-results
            front/test-results

  # JOB BUILD
  build:
    name: Build & Push Docker images
    runs-on: ubuntu-latest
    needs: tests

    permissions:
      contents: read
      packages: write

    env:
      REGISTRY: ghcr.io
      IMAGE_OWNER: c-pierre
      IMAGE_REPO: ocr-projet-6
      BRANCH_NAME: ${{ github.ref_name }}
      SHORT_SHA: ${{ github.sha }}

    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # Login to GHCR
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.APP_SECRET }}

      # Build & push back image (si existant)
      - name: Build & Push back image
        if: hashFiles('back/Dockerfile*') != ''
        uses: docker/build-push-action@v5
        with:
          context: ./back
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/${{ env.IMAGE_REPO }}/back:${{ github.ref_name//\//- }}-${{ github.sha }}

      # Build & push front image (si existant)
      - name: Build & Push front image
        if: hashFiles('front/Dockerfile*') != ''
        uses: docker/build-push-action@v5
        with:
          context: ./front
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/${{ env.IMAGE_REPO }}/front:${{ github.ref_name//\//- }}-${{ github.sha }}